frontend: 
	cd hemkraft

frontend_install:
	cd hemkraft; npm ci --legacy-peer-dep

start_frontend:
	cd hemkraft; npm run start

frontend_prod:
	cd hemkraft; npx serve -s build -p 80

jagat_backend_install:
	cd backend; /usr/bin/pip3 install -r requirements.txt

backend_install:
	cd backend; pip3 install -r requirements.txt

start_server:
	cd backend; python3 server.py

jagat_start_server:
	cd backend; /usr/bin/python3 server.py